from ultralytics import YOLO
from collections import deque
import numpy as np
import config

class ElephantCrossingDetector:
    def __init__(self):
        # Load your custom trained model
        # Using a try/except so if they run before training, it doesn't instantly crash but falls back to yolov8n
        # However, following the strict user prompt:
        import os
        model_path = "runs/train/elephant_v1/weights/best.pt"
        if not os.path.exists(model_path):
            print(f"WARNING: {model_path} not found. Ensure you ran train.py.")
            print("Falling back to yolov8n.pt for instantiation ONLY (won't detect 'elephants' accurately).")
            model_path = "yolov8n.pt"
            
        self.model = YOLO(model_path)
        self.conf_threshold = config.YOLO_CONF_THRESHOLD   # 0.50
        self.trail = deque(maxlen=config.FINGER_TRAIL_LENGTH)  # 10 frames
        self.sustained_count = 0
        self.last_bbox = None

    def detect(self, frame):
        results = self.model(
            frame,
            conf=self.conf_threshold,
            classes=[0, 1],      # Allow both 'Ele' (0) and 'elephant' (1) generated by Roboflow
            verbose=False
        )
        detections = []
        for r in results:
            for box in r.boxes:
                x1,y1,x2,y2 = map(int, box.xyxy[0])
                conf = float(box.conf[0])
                cx = (x1 + x2) // 2   # center x of bounding box
                cy = (y1 + y2) // 2   # center y of bounding box
                detections.append({
                    "bbox": (x1,y1,x2,y2),
                    "conf": conf,
                    "center": (cx, cy)
                })
        return detections

    def update_crossing_state(self, detections):
        """
        Crossing logic: track bounding box center X across frames.
        If center moves horizontally > HORIZONTAL_DELTA_MIN pixels
        within the trail window with < VERTICAL_DELTA_MAX vertical drift,
        it is a crossing event. Identical logic to finger tracker but
        applied to YOLO elephant bounding box center.
        """
        state = {
            "elephant_detected": False,
            "is_crossing": False,
            "direction": None,
            "delta_x": 0,
            "delta_y": 0,
            "conf": 0.0,
            "bbox": None,
            "trajectory": list(self.trail)
        }

        if not detections:
            self.sustained_count = 0
            state["trajectory"] = list(self.trail)
            return state

        best = max(detections, key=lambda d: d["conf"])
        cx, cy = best["center"]
        self.trail.append((cx, cy))
        self.last_bbox = best["bbox"]
        state["elephant_detected"] = True
        state["bbox"] = best["bbox"]
        state["conf"] = best["conf"]

        if len(self.trail) >= config.FINGER_TRAIL_LENGTH:
            oldest_x, oldest_y = self.trail[0]
            delta_x = cx - oldest_x
            delta_y = cy - oldest_y
            state["delta_x"] = delta_x
            state["delta_y"] = delta_y

            if (abs(delta_x) > config.HORIZONTAL_DELTA_MIN and
                abs(delta_y) < config.VERTICAL_DELTA_MAX):
                self.sustained_count += 1
                if self.sustained_count >= config.SUSTAINED_FRAMES:
                    state["is_crossing"] = True
                    state["direction"] = "RIGHT" if delta_x > 0 else "LEFT"
            else:
                self.sustained_count = 0

        state["trajectory"] = list(self.trail)
        return state
